version: '3.4'

services:
  mywebapi:
    image: mywebapi
    build:
      context: .
      dockerfile: exemplo-2/mywebapi/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
